import ast
import io
import tokenize
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src" / "kgllm_pharm"

FORBIDDEN = [
    "comprehensive",
    "cutting-edge",
    "seamlessly",
    "leveraging",
    "utilize",
    "delve",
    "holistic",
    "meticulously",
    "state-of-the-art",
    "reproduction of",
    "re-implementation",
    "as described by",
    "following the authors",
    "generated by",
    "ai-assisted",
]


def _sources() -> list[Path]:
    return sorted(SRC.rglob("*.py"))


def test_no_comments_or_docstrings_in_source() -> None:
    for path in _sources():
        text = path.read_text()
        for token in tokenize.generate_tokens(io.StringIO(text).readline):
            assert token.type != tokenize.COMMENT, f"comment in {path}"
        tree = ast.parse(text)
        for node in ast.walk(tree):
            if isinstance(node, ast.Module | ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef):
                assert ast.get_docstring(node) is None, f"docstring in {path}"


def test_no_forbidden_phrases_or_emoji() -> None:
    targets = [*_sources(), ROOT / "README.md", ROOT / "Makefile"]
    for path in targets:
        raw = path.read_text()
        lowered = raw.lower()
        for phrase in FORBIDDEN:
            assert phrase not in lowered, f"{phrase} in {path}"
        for char in raw:
            point = ord(char)
            assert not (0x1F000 <= point <= 0x1FAFF), f"emoji in {path}"
            assert not (0x2600 <= point <= 0x27BF), f"emoji in {path}"
